name: lucy-teamcloud-onprem

services:
  init-secrets:
    image: localhost/lucy-teamcloud-onprem-init-secrets:offline
    platform: ${TARGET_PLATFORM:-linux/amd64}
    restart: "no"
    network_mode: none
    environment:
      EXTERNAL_URL: ${EXTERNAL_URL}
    volumes:
      - ./secrets:/secrets:z
      - ./nginx/certs:/certs:z
