services:
  gw:
    ports: !override
      - "18080:80"
      - "18443:443"

  init-secrets:
    image: lucy-teamcloud-onprem-init-secrets:offline
    build:
      context: ./init-secrets
    platform: ${TARGET_PLATFORM:-linux/amd64}
    volumes: !override
      - ./secrets:/secrets
      - ./nginx/certs:/certs
    command: null

  broker:
    image: eclipse-mosquitto:2.0.22
    platform: ${TARGET_PLATFORM:-linux/amd64}
