services:
  init-secrets:
    image: localhost/lucy-teamcloud-onprem-init-secrets:offline
    volumes: !override
      - ./secrets:/secrets:z
      - ./nginx/certs:/certs:z

  gw:
    volumes: !override
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro,z
      - ./nginx/certs:/etc/nginx/certs:ro,z
    depends_on:
      - db
      - git
      - auth-be
      - auth-fe
      - tc-be
      - tc-fe

  git:
    volumes: !override
      - ./git/data:/data:z
      - ./git/app.ini:/app.ini.default:ro,z
      - ./git/gitea-entrypoint.sh:/gitea-entrypoint.sh:ro,z
      - ./secrets:/run/secrets:ro,z
    depends_on:
      - db

  db:
    volumes: !override
      - ./postgres/data:/var/lib/postgresql/data:z
      - ./postgres/initdb:/docker-entrypoint-initdb.d:ro,z

  broker:
    image: localhost/lucy-teamcloud-onprem-broker:offline
    volumes: !override
      - ./broker/logs:/vernemq/log:z
      - ./broker/data:/vernemq/data:z

  auth-be:
    user: "0:0"
    depends_on:
      - db
    volumes: !override
      - ./secrets:/run/secrets:ro,z
      - ./auth/auth-entrypoint.sh:/auth-entrypoint.sh:ro,z
      - ./nginx/certs/server.crt:/certs/server.crt:ro,z
      - ./auth/logs:/app/logs:z

  tc-be:
    user: "0:0"
    depends_on:
      - db
    volumes: !override
      - ./secrets:/run/secrets:ro,z
      - ./tc/tc-entrypoint.sh:/tc-entrypoint.sh:ro,z
      - ./license:/app/license:ro,z
      - ./nginx/certs/server.crt:/certs/server.crt:ro,z
      - ./tc/logs:/app/logs:z
