server {
  listen 443 ssl;
  server_name git.dev.edencrew.io;

  include /etc/nginx/conf.d/20_tls_server.inc;
  client_max_body_size 0;

  location / {
    include /etc/nginx/conf.d/30_policy_http_proxy.inc;

    set $upstream teamcloud-network-gitea:3000;
    proxy_pass http://$upstream;
  }
}