server {
  listen 443 ssl;
  server_name cloud.dev.edencrew.io;

  include /etc/nginx/conf.d/20_tls_server.inc;

  location ^~ /api {
    include /etc/nginx/conf.d/30_policy_http_proxy.inc;

    set $be_upstream teamcloud-network-teamcloud-be:8080;
    proxy_pass http://$be_upstream;
  }

  # FE
  location / {
    include /etc/nginx/conf.d/30_policy_http_proxy.inc;

    set $fe_upstream teamcloud-network-teamcloud-fe:80;
    proxy_pass http://$fe_upstream;
  }
}