server {
  listen 80;
  server_name mqtt.dev.edencrew.io;

  location / {
    include /etc/nginx/conf.d/31_policy_http_ws_proxy.inc;

    set $upstream teamcloud-network-mqtt:9001;
    proxy_pass http://$upstream;
  }
}