#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
    CREATE DATABASE lucy_auth OWNER $DB_USERNAME;
    CREATE DATABASE lucy_teamcloud OWNER $DB_USERNAME;
    CREATE DATABASE git OWNER $DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE lucy_auth TO $DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE lucy_teamcloud TO $DB_USERNAME;
    GRANT ALL PRIVILEGES ON DATABASE gitea TO $DB_USERNAME;
EOSQL
