#!/usr/bin/env bash
set -Eeo pipefail

# load-compose-images.sh
#
# Recommended location:
#   <project-root>/scripts/load-compose-images.sh
#
# Purpose:
#   Verify and load a Docker image archive exported by export-compose-images.sh
#   on an offline / air-gapped Linux server.
#
# What it does:
#   1. Checks Docker installation and daemon status.
#   2. Finds the image archive automatically, or uses the provided archive path.
#   3. Verifies SHA256 checksum if .sha256 file exists.
#   4. Verifies gzip integrity for .tar.gz / .tgz archives.
#   5. Loads either a standard docker-save archive or a Podman-safe bundle.
#   6. Verifies expected images from *.archive-images.txt / *.images.txt if available.
#
# Compatibility:
#   - Bash 3+ compatible.
#   - Linux/macOS compatible, but intended for offline Linux servers.
#
# Why not `set -u`?
#   Bash 3 with empty arrays can fail unexpectedly. This script avoids nounset
#   for portability and validates required values explicitly.

SCRIPT_VERSION="1.1.2"

show_help() {
  cat <<'EOF'
load-compose-images.sh

DESCRIPTION
  Verify and load a Docker image archive on an offline / air-gapped server.

  This script is intended to be used with archives generated by:
    export-compose-images.sh

  It supports both:
    - standard docker save archives
    - Podman-safe image-by-image bundle archives from export-compose-images.sh

RECOMMENDED LOCATION
  <project-root>/scripts/load-compose-images.sh

USAGE
  ./scripts/load-compose-images.sh [OPTIONS] [ARCHIVE_PATH]

OPTIONS
  -h, --help
      Show this help message and exit.

  -v, --version
      Show script version and exit.

  --skip-checksum
      Skip SHA256 checksum verification even if a .sha256 file exists.

  --skip-gzip-test
      Skip gzip integrity verification.

  --skip-image-verify
      Skip post-load image existence verification using *.images.txt.

  --compose-up
      After image load and verification, run:
        ./scripts/preflight-onprem.sh --compose-up

      This requires compose files to exist in the project root.

ENVIRONMENT VARIABLES
  PROJECT_ROOT
      Explicit project root path.
      Default:
        If script is inside ./scripts, parent directory of ./scripts.
        Otherwise, the directory containing this script.

      Example:
        PROJECT_ROOT=/path/to/project ./scripts/load-compose-images.sh

  IMAGES_DIR
      Directory that contains the image archive.
      Default: <project-root>/images

      Example:
        IMAGES_DIR=/mnt/usb/images ./scripts/load-compose-images.sh

  ARCHIVE_PATH
      Explicit archive path.
      Same effect as passing ARCHIVE_PATH as the first positional argument.

      Example:
        ARCHIVE_PATH=./images/onprem-images.tar.gz ./scripts/load-compose-images.sh

  CHECKSUM_FILE
      Explicit checksum file path.
      Default: <archive>.sha256

  IMAGE_LIST_FILE
      Explicit image list file path.
      Default:
        For archive:
          lucy-images-linux-amd64.tar.gz
        script first looks for:
          lucy-images-linux-amd64.archive-images.txt
        then falls back to:
          lucy-images-linux-amd64.images.txt

EXAMPLES
  Auto-detect a single archive under ./images:
    ./scripts/load-compose-images.sh

  Load a specific archive:
    ./scripts/load-compose-images.sh ./images/lucy-teamcloud-onprem-images-linux-amd64.tar.gz

  Use an archive copied to /tmp:
    ./scripts/load-compose-images.sh /tmp/lucy-teamcloud-onprem-images-linux-amd64.tar.gz

  Skip checksum:
    ./scripts/load-compose-images.sh --skip-checksum ./images/images.tar.gz

  Load and start compose:
    ./scripts/load-compose-images.sh --compose-up ./images/images.tar.gz

OFFLINE SERVER FLOW
  1. Copy files to offline server:
       images/*.tar.gz
       images/*.tar.gz.sha256
       images/*.images.txt

  2. Run:
       ./scripts/load-compose-images.sh

  3. Optionally start services:
       ./scripts/preflight-onprem.sh --compose-up

EOF
}

log() {
  printf '\n\033[1;34m[INFO]\033[0m %s\n' "$*"
}

warn() {
  printf '\n\033[1;33m[WARN]\033[0m %s\n' "$*" >&2
}

die() {
  printf '\n\033[1;31m[ERROR]\033[0m %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

is_gzip_archive() {
  case "$1" in
    *.tar.gz|*.tgz)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

script_dir() {
  local src="${BASH_SOURCE[0]}"
  while [ -L "$src" ]; do
    local dir
    dir="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
    src="$(readlink "$src")"
    case "$src" in
      /*) ;;
      *) src="$dir/$src" ;;
    esac
  done
  cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd
}

resolve_project_root() {
  local sdir="$1"
  local root=""

  if [ -n "${PROJECT_ROOT:-}" ]; then
    root="$PROJECT_ROOT"
  else
    case "$(basename "$sdir")" in
      scripts)
        root="$(dirname "$sdir")"
        ;;
      *)
        root="$sdir"
        ;;
    esac
  fi

  (cd "$root" >/dev/null 2>&1 && pwd) || die "Project root not found or not accessible: $root"
}

resolve_path_from_root() {
  local path="$1"

  case "$path" in
    /*)
      printf '%s' "$path"
      ;;
    *)
      printf '%s/%s' "$ROOT_DIR" "$path"
      ;;
  esac
}

archive_basename_without_extensions() {
  local file="$1"
  local base
  base="$(basename "$file")"

  case "$base" in
    *.tar.gz)
      base="${base%.tar.gz}"
      ;;
    *.tgz)
      base="${base%.tgz}"
      ;;
    *.tar)
      base="${base%.tar}"
      ;;
    *)
      base="${base%.*}"
      ;;
  esac

  printf '%s' "$base"
}

default_image_list_file() {
  local archive="$1"
  local base_name="$2"
  local archive_images_file
  local full_images_file

  archive_images_file="$(dirname "$archive")/$base_name.archive-images.txt"
  full_images_file="$(dirname "$archive")/$base_name.images.txt"

  if [ -f "$archive_images_file" ]; then
    printf '%s' "$archive_images_file"
  else
    printf '%s' "$full_images_file"
  fi
}

find_single_archive() {
  local dir="$1"

  [ -d "$dir" ] || die "Images directory not found: $dir"

  local matches=""
  local count=0
  local f=""

  for f in "$dir"/*.tar.gz "$dir"/*.tgz "$dir"/*.tar; do
    [ -f "$f" ] || continue
    matches="${matches}${f}
"
    count=$((count + 1))
  done

  if [ "$count" -eq 0 ]; then
    die "No image archive found in: $dir"
  fi

  if [ "$count" -gt 1 ]; then
    printf '%s\n' "$matches" >&2
    die "Multiple image archives found. Pass one explicitly: ./scripts/load-compose-images.sh <ARCHIVE_PATH>"
  fi

  printf '%s' "$matches" | sed '/^[[:space:]]*$/d' | head -n 1
}

verify_checksum() {
  local archive="$1"
  local checksum_file="$2"

  if [ "$SKIP_CHECKSUM" = "1" ]; then
    warn "Skipping checksum verification by request."
    return 0
  fi

  if [ ! -f "$checksum_file" ]; then
    warn "Checksum file not found. Skipping checksum verification: $checksum_file"
    return 0
  fi

  log "Verifying SHA256 checksum: $checksum_file"

  if command -v sha256sum >/dev/null 2>&1; then
    (
      cd "$(dirname "$archive")"
      sha256sum -c "$(basename "$checksum_file")"
    )
  elif command -v shasum >/dev/null 2>&1; then
    (
      cd "$(dirname "$archive")"
      shasum -a 256 -c "$(basename "$checksum_file")"
    )
  else
    warn "Neither sha256sum nor shasum found. Skipping checksum verification."
  fi
}

verify_gzip() {
  local archive="$1"

  if [ "$SKIP_GZIP_TEST" = "1" ]; then
    warn "Skipping gzip test by request."
    return 0
  fi

  case "$archive" in
    *.tar.gz|*.tgz)
      require_cmd gzip
      log "Testing gzip integrity..."
      gzip -t "$archive"
      ;;
    *)
      log "Archive is not gzip-compressed. Skipping gzip test."
      ;;
  esac
}

docker_load_archive() {
  local archive="$1"

  if archive_is_image_bundle "$archive"; then
    load_image_bundle "$archive"
  else
    log "Loading Docker images from archive..."
    docker load -i "$archive"
  fi
}

archive_is_image_bundle() {
  local archive="$1"

  if is_gzip_archive "$archive"; then
    gzip -cd "$archive" | tar -tf - 2>/dev/null | grep -qx 'lucy-image-bundle-v1/manifest.tsv'
  else
    tar -tf "$archive" 2>/dev/null | grep -qx 'lucy-image-bundle-v1/manifest.tsv'
  fi
}

extract_archive_to_dir() {
  local archive="$1"
  local dest="$2"

  if is_gzip_archive "$archive"; then
    gzip -cd "$archive" | tar -xf - -C "$dest"
  else
    tar -xf "$archive" -C "$dest"
  fi
}

load_image_bundle() {
  local archive="$1"
  local tmp_dir bundle_dir manifest index image rel_path loaded

  require_cmd tar

  tmp_dir="$(mktemp -d)"
  bundle_dir="$tmp_dir/lucy-image-bundle-v1"
  manifest="$bundle_dir/manifest.tsv"

  log "Loading Docker images from image-by-image bundle..."
  extract_archive_to_dir "$archive" "$tmp_dir"
  [ -f "$manifest" ] || die "Bundle manifest not found after extraction: $manifest"

  loaded=0
  while IFS="$(printf '\t')" read -r index image rel_path; do
    [ -n "$index" ] || continue
    [ -n "$image" ] || die "Malformed bundle manifest line: missing image"
    [ -n "$rel_path" ] || die "Malformed bundle manifest line for image: $image"
    [ -f "$bundle_dir/$rel_path" ] || die "Bundle image archive not found: $rel_path"

    log "Loading bundled image: $image"
    docker load -i "$bundle_dir/$rel_path"
    loaded=$((loaded + 1))
  done < "$manifest"

  rm -rf "$tmp_dir"

  if [ "$loaded" -eq 0 ]; then
    die "Bundle manifest contained no images."
  fi
}

ensure_local_image_available() {
  local img="$1"
  local fallback=""
  local docker_hub_name=""

  if docker image inspect "$img" >/dev/null 2>&1; then
    return 0
  fi

  case "$img" in
    localhost/*)
      fallback="${img#localhost/}"
      if [ -n "$fallback" ] && docker image inspect "$fallback" >/dev/null 2>&1; then
        docker image tag "$fallback" "$img" >/dev/null 2>&1 || return 1
        printf '  INFO Retagged local image for Podman short-name safety: %s -> %s\n' "$fallback" "$img"
        return 0
      fi
      ;;
    docker.io/library/*)
      docker_hub_name="${img#docker.io/library/}"
      fallback="localhost/$docker_hub_name"
      if [ -n "$docker_hub_name" ] && docker image inspect "$fallback" >/dev/null 2>&1; then
        docker image tag "$fallback" "$img" >/dev/null 2>&1 || return 1
        printf '  INFO Retagged Docker Hub image loaded by Podman: %s -> %s\n' "$fallback" "$img"
        return 0
      fi

      fallback="$docker_hub_name"
      if [ -n "$docker_hub_name" ] && docker image inspect "$fallback" >/dev/null 2>&1; then
        docker image tag "$fallback" "$img" >/dev/null 2>&1 || return 1
        printf '  INFO Retagged Docker Hub short-name image: %s -> %s\n' "$fallback" "$img"
        return 0
      fi
      ;;
  esac

  return 1
}

image_id() {
  docker image inspect "$1" --format '{{.Id}}' 2>/dev/null || true
}

remove_image_alias_if_same_id() {
  local canonical="$1"
  local alias="$2"
  local canonical_id alias_id

  [ "$canonical" != "$alias" ] || return 0

  canonical_id="$(image_id "$canonical")"
  alias_id="$(image_id "$alias")"

  if [ -n "$canonical_id" ] && [ "$canonical_id" = "$alias_id" ]; then
    if docker image rmi "$alias" >/dev/null 2>&1; then
      printf '  INFO Removed redundant image alias: %s\n' "$alias"
    else
      printf '  WARN Could not remove redundant image alias, continuing: %s\n' "$alias" >&2
    fi
  fi
}

cleanup_redundant_image_aliases() {
  local img="$1"
  local docker_hub_name=""

  case "$img" in
    docker.io/library/*)
      docker_hub_name="${img#docker.io/library/}"
      remove_image_alias_if_same_id "$img" "localhost/$docker_hub_name"
      ;;
  esac
}

verify_images_loaded() {
  local image_list_file="$1"

  if [ "$SKIP_IMAGE_VERIFY" = "1" ]; then
    warn "Skipping image verification by request."
    return 0
  fi

  if [ ! -f "$image_list_file" ]; then
    warn "Image list file not found. Skipping image verification: $image_list_file"
    return 0
  fi

  log "Verifying loaded images from: $image_list_file"

  local missing=0
  local img=""

  while IFS= read -r img; do
    [ -n "$img" ] || continue

    if ensure_local_image_available "$img"; then
      cleanup_redundant_image_aliases "$img"
      printf '  OK   %s\n' "$img"
    else
      printf '  MISS %s\n' "$img" >&2
      missing=$((missing + 1))
    fi
  done < "$image_list_file"

  if [ "$missing" -gt 0 ]; then
    die "$missing expected image(s) were not found after docker load."
  fi
}

verify_image_id_sanity() {
  local image_list_file="$1"

  if [ "$SKIP_IMAGE_VERIFY" = "1" ]; then
    return 0
  fi

  if [ ! -f "$image_list_file" ]; then
    return 0
  fi

  local img id first_id first_img total same_id
  first_id=""
  first_img=""
  total=0
  same_id=0

  while IFS= read -r img; do
    [ -n "$img" ] || continue
    id="$(docker image inspect "$img" --format '{{.Id}}' 2>/dev/null || true)"
    [ -n "$id" ] || continue

    total=$((total + 1))
    if [ -z "$first_id" ]; then
      first_id="$id"
      first_img="$img"
    fi
    if [ "$id" = "$first_id" ]; then
      same_id=$((same_id + 1))
    fi
  done < "$image_list_file"

  if [ "$total" -ge 3 ] && [ "$same_id" -eq "$total" ]; then
    die "Loaded image sanity check failed: $total expected images all resolve to the same image ID as $first_img. The archive or tag state is corrupt; re-export with the current export-compose-images.sh and reload."
  fi
}

detect_base_compose_file() {
  local candidates="docker-compose.yaml docker-compose.yml compose.yaml compose.yml"
  local f

  for f in $candidates; do
    if [ -f "$ROOT_DIR/$f" ]; then
      printf '%s' "$ROOT_DIR/$f"
      return 0
    fi
  done

  return 1
}

run_compose_up() {
  local preflight="$ROOT_DIR/scripts/preflight-onprem.sh"
  [ -x "$preflight" ] || die "preflight script not found or not executable: $preflight"
  log "Running preflight and compose up..."
  "$preflight" --compose-up
}


parse_args() {
  SKIP_CHECKSUM=0
  SKIP_GZIP_TEST=0
  SKIP_IMAGE_VERIFY=0
  COMPOSE_UP=0
  POSITIONAL_ARCHIVE=""

  while [ "$#" -gt 0 ]; do
    case "$1" in
      -h|--help)
        show_help
        exit 0
        ;;
      -v|--version)
        echo "load-compose-images.sh $SCRIPT_VERSION"
        exit 0
        ;;
      --skip-checksum)
        SKIP_CHECKSUM=1
        ;;
      --skip-gzip-test)
        SKIP_GZIP_TEST=1
        ;;
      --skip-image-verify)
        SKIP_IMAGE_VERIFY=1
        ;;
      --compose-up)
        COMPOSE_UP=1
        ;;
      -*)
        die "Unknown option: $1

Run './scripts/load-compose-images.sh --help' for usage."
        ;;
      *)
        if [ -n "$POSITIONAL_ARCHIVE" ]; then
          die "Only one ARCHIVE_PATH can be provided."
        fi
        POSITIONAL_ARCHIVE="$1"
        ;;
    esac
    shift
  done
}

main() {
  parse_args "$@"

  require_cmd docker
  require_cmd tar
  docker info >/dev/null 2>&1 || die "Docker daemon is not running or current user cannot access Docker."

  local sdir
  sdir="$(script_dir)"

  ROOT_DIR="$(resolve_project_root "$sdir")"

  IMAGES_DIR="${IMAGES_DIR:-$ROOT_DIR/images}"
  IMAGES_DIR="$(resolve_path_from_root "$IMAGES_DIR")"

  local archive=""

  if [ -n "${ARCHIVE_PATH:-}" ]; then
    archive="$ARCHIVE_PATH"
  elif [ -n "$POSITIONAL_ARCHIVE" ]; then
    archive="$POSITIONAL_ARCHIVE"
  else
    archive="$(find_single_archive "$IMAGES_DIR")"
  fi

  archive="$(resolve_path_from_root "$archive")"
  [ -f "$archive" ] || die "Archive file not found: $archive"

  local base_name
  base_name="$(archive_basename_without_extensions "$archive")"

  local checksum_file="${CHECKSUM_FILE:-$archive.sha256}"
  checksum_file="$(resolve_path_from_root "$checksum_file")"

  local image_list_file="${IMAGE_LIST_FILE:-$(default_image_list_file "$archive" "$base_name")}"
  image_list_file="$(resolve_path_from_root "$image_list_file")"

  log "Project root: $ROOT_DIR"
  log "Images directory: $IMAGES_DIR"
  log "Archive: $archive"
  log "Checksum file: $checksum_file"
  log "Image list file: $image_list_file"

  verify_checksum "$archive" "$checksum_file"
  verify_gzip "$archive"
  docker_load_archive "$archive"
  verify_images_loaded "$image_list_file"
  verify_image_id_sanity "$image_list_file"

  if [ "$COMPOSE_UP" = "1" ]; then
    run_compose_up
  fi

  log "Load complete."

  cat <<EOF

Next step:
  cd "$ROOT_DIR"
  ./scripts/preflight-onprem.sh --compose-up

EOF
}

main "$@"
